// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/Base/app-header.vue')['default']
    AppScrollButton: typeof import('./src/components/Base/app-scroll-button.vue')['default']
    GetInButtons: typeof import('./src/components/get-in-buttons.vue')['default']
    IndexHero: typeof import('./src/components/index-hero.vue')['default']
    IndexHeroButton: typeof import('./src/components/index-hero-button.vue')['default']
    IndexInstall: typeof import('./src/components/index-install.vue')['default']
    IndexTellme: typeof import('./src/components/index-tellme.vue')['default']
    IndexWhatIs: typeof import('./src/components/index-what-is.vue')['default']
    IndexWhatIsIcon: typeof import('./src/components/index-what-is-icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
